### ISSUE TITLE
canonical-data.json: Compliance with JSON Schema

### ISSUE THREAD

**Issue by rbasso** [exercism/x-common#625]
Now that #602 was merged, it would be great to have all the `canonical-data.json` files compliant with the JSON Schema, so that we could automatically check them for errors in the future.

At the moment, we have 74 `canonical-data.json` files, but only 3 are compliant.

When porting the files, I guess it would be nice to follow a few guidelines to make reviewing easier:
- Distinct commits with the following:
    1. `exercise-name: Make canonical-data.json compliant`, containing the minimal changes to make the test suite compliant.
    2. `exercise-name: Fix canonical-data.json formatting`, with the changes needed to make it readable again.
- pull-request's title: `exercise-name: Make exercise schema-compliant`
- pull-request's body: at least a line containing `Related to #625`.
- `version` should start at **1.0.0** and follow the `exercise` property.

Unless there is already a standard in place that I don't know, I suggest formatting with 2-spaces indentation in the second commit, for consistency, which is already the default when running `jq '.' canonical-data.json`.

Of course, most of the exercises will demand additional changes to a standard formatting, to make them more compact and readable.

**Edit:** Just to be clear, this issue is **not about style** in designing the test suite. *Changes that go beyond fixing the test suite to be compliant and fix it to be consistently formatted after that should be avoided here!*

---

#### `canonical-data.json` compliance

- [x] acronym #626
- [x] allergies #628
- [x] all-your-base #630
- [x] alphametics #675 
- [x] anagram #631
- [x] atbash-cipher #632 
- [x] beer-song #661 / #694 
- [x] binary #644 
- [x] binary-search #676 
- [x] bob #636
- [x] book-store #635
- [x] bowling #677 
- [x] bracket-push #680 
- [x] change #641 
- [x] circular-buffer #681 
- [x] clock #669 
- [x] connect #670 
- [x] crypto-square #652 
- [x] custom-set #672 
- [x] diamond #612
- [x] difference-of-squares #653 
- [x] dominoes #682 
- [x] etl #654 
- [x] flatten-array #683 
- [x] food-chain #684 
- [x] forth #688 
- [x] gigasecond #685 
- [x] grains #642 
- [x] grep #712
- [x] hamming #627
- [x] hello-world #629 
  - [x] Need bump to 1.0.0
- [x] isogram #686 
- [x] largest-series-product #689 
- [x] leap #633
- [x] list-ops #690 
- [x] luhn #643
- [x] markdown #691 
- [x] meetup #663 
- [x] minesweeper #664 
- [x] nth-prime #665 
- [x] nucleotide-count #666 
- [x] ocr-numbers #667 
- [x] pangram #687 
- [x] pascals-triangle #668 
- [x] perfect-numbers #611
- [x] phone-number #678 
- [x] pig-latin #646 
- [x] pov #704 
- [x] prime-factors #695 
- [x] queen-attack #655 
- [x] rail-fence-cipher #696 
- [x] raindrops #637 
- [x] react #697 
- [x] rectangles #698 
- [x] rna-transcription #638 
- [x] robot-simulator #656 
- [x] roman-numerals #711 
- [x] rotational-cipher #701 
- [x] run-length-encoding #702 
- [x] say #647 
- [x] scrabble-score #639 
- [x] secret-handshake #657 
- [x] sieve #649 
- [x] space-age #703 
- [x] sublist #705 
- [x] sum-of-multiples #650 
- [x] tournament #717
- [x] transpose #706 
- [x] triangle #651 
- [x] trinary #645 
- [x] two-bucket #713 
- [x] variable-length-quantity #708
- [x] word-count #634 
- [x] wordy #648

**Comment by petertseng** [comment]
The final goal here is that we will be able to run every canonical-data.json through a schema check, right?

Then can I propose we do not wait until all canonical-data.json are compliant before starting to do that?

Let's start check them all ASAP, and allow those listed in a file named allowed-schema-failures (or something) to fail.

The goal of course will be to drive the number of lines in the file down to zero.

**Comment by petertseng** [comment]
Because we wouldn't want a file that was compliant to fall out of compliance while this project is underway.

**Comment by rbasso** [comment]
If anyone wants to port and exercise to the new schema, I is a good idea to say here, so that we don't make useless duplicated work.

@rbasso: `acronym`, `allergies`

**Comment by kotp** [comment]
Working on Hamming

**Comment by rbasso** [comment]
Working on: `hello-world`, `all-your-base`

**Comment by catb0t** [comment]
I'll tackle `leap` and `word-count`.

**Comment by rbasso** [comment]
Working on: `anagram`, `atbash-cipher` and `bob`.

**Comment by rpottsoh** [comment]
I've got `book-store`.

**Comment by rbasso** [comment]
Working on `raindrops`, `rna-transcription` and `scrabble-score`.

**Comment by rbasso** [comment]
Working on `change`, `grains` and `luhn`.

**Comment by rbasso** [comment]
Working on `binary` and `trinary`, deprecated exercises.

**Comment by rbasso** [comment]
Working on `pig-latin`, `say` and `wordy`.

**Comment by rbasso** [comment]
Working on `sieve`, `sum-of-multiples` and `triangle`

**Comment by rbasso** [comment]
Working on `crypto-square`, `difference-of-squares` and `etl`.

**Comment by rbasso** [comment]
Working on `queen-attack`, `robot-simulator` and `secret-handshake`.

**Comment by rbasso** [comment]
Working on `meetup`, `minesweeper` and `nth-prime`.

**Comment by tejasbubane** [comment]
Working on adding schema validation to travis.

**Comment by kotp** [comment]
I will grab `beer-song` due to #661

**Comment by rbasso** [comment]
Working on `nucleotide-count`, `ocr-numbers` and `pascals-triangle`.

**Comment by rbasso** [comment]
Working on `clock`, `comment` and `custom-set`.

**Comment by rbasso** [comment]
Working on `alphametics`, `binary-search` and `bowling`.

**Comment by rbasso** [comment]
Working on `bracket-push`, `circular-buffer`, `dominoes`, `flatten-array` and `food-chain`.

**Comment by tejasbubane** [comment]
working on `phone-number`. 

@rbasso I am a little confused with the `property` field. Since it is required in all test cases, is that supposed to be the function/method name in the implementation? The [description here](https://github.com/exercism/x-common/blob/master/canonical-schema.json#L115) is not very useful.

**Comment by rbasso** [comment]
> The description here is not very useful.

Sorry for the description!

The `property` is a string that uniquely identifies a *test type*.

In test-suite-generation terms, it is a reference to an external test-logic, a way to turn the test data in a real test. Ops, I guess I made the explanation worse. 😁  

> I am a little confused with the property field. Since it is required in all test cases, is that supposed to be the function/method name in the implementation?

In most of the situations, yes! It can be the name of a function! Just keep in mind that if the tests use the same function (test logic), they need to have the same `property`.

**Comment by tejasbubane** [comment]
Working on `isogram` and `pangram`.

**Comment by rbasso** [comment]
Working on `forth`, `grep` and `largest-series-product`. We are almost there...

**Comment by rbasso** [comment]
Working on `list-ops`, `markdown` and `pov`.

**Comment by tejasbubane** [comment]
> grep needs a complete redesign to match the new schema, because it encodes files in the JSON. Not touching it for now.

@rbasso Does this mean we need a way to ignore some exercises from the CI?

**Comment by rbasso** [comment]
Don't worry about that for now, @tejasbubane. I already have an idea about who to sidestep the `grep` problem, but I'm waiting to see if I find more incompatible exercises to so that we can rewrite them together in a more consistent way.

**Comment by rbasso** [comment]
Working on `prime-factor`, `rail-fence-cipher`, `react` and `rectangles`.

**Comment by rbasso** [comment]
Working on `rotational-cipher`, `run-length-encoding` and `space-age`.

**Comment by petertseng** [comment]
I guess I have to do `pov`.

**Comment by kotp** [comment]
Make sure to see @rbasso concerns with pov and grep, among others... referenced #699

**Comment by rbasso** [comment]
Thanks, @petertseng ! `pov` is the hardest by far...

**Comment by rbasso** [comment]
Working on `sublist` and `transpose`.

**Comment by rbasso** [comment]
Working on `two-bucket` and `variable-length-quantity`.

**Comment by rbasso** [comment]
People, we are at [full compliance with the JSON schema](https://travis-ci.org/exercism/x-common/builds/210239110) at the moment.

**Comment by kotp** [comment]
Now we will party like it's 18 years ago!

**Comment by rbasso** [comment]
I'm glad to say that, after something around 150 commits (+75 merges), we are almost done. We just need some eyes in exercism/x-common#658 to review enforcing it in Travis-CI, then this chapter of **the standardization saga** will be over. 🎉  🎊 

I know that I'm guilty of rushing the conversion to this new schema a little, but we did all possible to avoid changes in the test contents, so I just hope no one will be mad with me. :grin:

In the few cases where meaningful test-data changes where really needed, we bumped the `version` to `1.1.0`, so it should be easy to identify those exercises.

I'm sorry for adding some completely unhelpful description to tests that where missing them. Some `property` names I added are also regrettably horrible. 

That said, the changes are not forever, and I expect the errors and bad decisions will be fixed someday.

Thanks to everybody who joined this task force! 👍

Now, if you excuse me, I'll try a JSON-detox for a while. 😷
